logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: PetCareBENag
    root_packages: com.apps.petcare
server:
  port: 8080
spring:
  datasource:
           driver-class-name: org.postgresql.Driver
           url: jdbc:postgresql://3.92.222.200:8127/postgres
           password: password
           username: postgres
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false
eclipselink:
   ddl:
       auto:
            create:
                   delete: false